#!/usr/bin/env python3
"""Generate the native Owner API contract manifest from canonical OpenAPI."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "docs/api/owner-v1.openapi.yaml"
EXAMPLES_PATH = ROOT / "docs/api/owner-v1.examples.json"
SWIFT_PATH = (
    ROOT
    / "native/PhotosByElieBackstage/Sources/OwnerCore/Generated/OwnerContract.generated.swift"
)
FIXTURE_PATH = (
    ROOT
    / "native/PhotosByElieBackstage/Tests/OwnerCoreTests/Fixtures/owner-api-examples.json"
)

REQUIRED_EXAMPLE_SECTIONS = {
    "authentication",
    "pagination",
    "error",
    "idempotency",
    "progress",
}
REQUIRED_OPERATIONS = {
    "createOwnerTokens",
    "refreshOwnerTokens",
    "listActions",
    "createAction",
    "transitionAction",
    "getAccessState",
    "querySidecarDecisions",
    "saveDeliverable",
    "submitRenderJob",
    "getRenderJob",
}


def parse_operations(spec: str) -> list[tuple[str, str, str]]:
    operations: list[tuple[str, str, str]] = []
    current_path: str | None = None
    current_method: str | None = None
    in_paths = False
    for line in spec.splitlines():
        if line == "paths:":
            in_paths = True
            continue
        if line == "components:":
            break
        if not in_paths:
            continue
        path_match = re.match(r"^  (/[^:]+):$", line)
        if path_match:
            current_path = path_match.group(1)
            current_method = None
            continue
        method_match = re.match(r"^    (get|post|put|patch|delete):$", line)
        if method_match:
            current_method = method_match.group(1).upper()
            continue
        operation_match = re.match(r"^      operationId: ([A-Za-z0-9_]+)$", line)
        if operation_match and current_path and current_method:
            operations.append((operation_match.group(1), current_method, current_path))
    return operations


def parse_schema_names(spec: str) -> list[str]:
    marker = "  schemas:\n"
    if marker not in spec:
        raise ValueError("OpenAPI components.schemas is missing")
    tail = spec.split(marker, 1)[1]
    return sorted(
        match.group(1)
        for match in re.finditer(r"^    ([A-Za-z][A-Za-z0-9]+):$", tail, re.MULTILINE)
    )


def swift_identifier(value: str) -> str:
    return value[:1].lower() + value[1:]


def render_swift(spec: str, examples: dict[str, object]) -> str:
    operations = parse_operations(spec)
    operation_names = {name for name, _, _ in operations}
    missing = sorted(REQUIRED_OPERATIONS - operation_names)
    if missing:
        raise ValueError(f"OpenAPI is missing required operations: {', '.join(missing)}")
    missing_examples = sorted(REQUIRED_EXAMPLE_SECTIONS - examples.keys())
    if missing_examples:
        raise ValueError(f"Examples are missing sections: {', '.join(missing_examples)}")

    digest = hashlib.sha256(spec.encode("utf-8")).hexdigest()
    operation_cases = "\n".join(
        f'        case {swift_identifier(name)} = "{name}"'
        for name, _, _ in sorted(operations)
    )
    endpoint_rows = "\n".join(
        f'        .{swift_identifier(name)}: Endpoint(method: "{method}", path: "{path}"),'
        for name, method, path in sorted(operations)
    )
    schemas = ", ".join(f'"{name}"' for name in parse_schema_names(spec))
    example_sections = ", ".join(f'"{name}"' for name in sorted(examples))
    return f"""// Generated by scripts/generate_owner_swift_contract.py. Do not edit.
import Foundation

public enum OwnerContract {{
    public static let openAPIVersion = "1.0.0"
    public static let specSHA256 = "{digest}"
    public static let schemaNames = [{schemas}]
    public static let exampleSections = [{example_sections}]

    public enum Operation: String, CaseIterable, Sendable {{
{operation_cases}
    }}

    public struct Endpoint: Sendable, Equatable {{
        public let method: String
        public let path: String

        public init(method: String, path: String) {{
            self.method = method
            self.path = path
        }}
    }}

    public static let endpoints: [Operation: Endpoint] = [
{endpoint_rows}
    ]
}}
"""


def normalized_examples(examples: dict[str, object]) -> str:
    return json.dumps(examples, indent=2, sort_keys=True) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return True
    if check:
        print(f"Owner API generated artifact is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files drift")
    args = parser.parse_args()

    spec = SPEC_PATH.read_text(encoding="utf-8")
    examples = json.loads(EXAMPLES_PATH.read_text(encoding="utf-8"))
    swift = render_swift(spec, examples)
    fixture = normalized_examples(examples)
    results = [
        write_or_check(SWIFT_PATH, swift, args.check),
        write_or_check(FIXTURE_PATH, fixture, args.check),
    ]
    if args.check and not all(results):
        print(
            "Run `python3 scripts/generate_owner_swift_contract.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    print(
        f"Owner API contract is current ({len(parse_operations(spec))} operations, "
        f"{len(parse_schema_names(spec))} schemas)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
