import AppKit
import SwiftUI

/// Preserves the native Waste Basket table viewport while SwiftUI replaces its
/// sorted rows. A passive SwiftUI scroll-position binding does not receive the
/// visible row IDs from `Table`, so the AppKit clip-view offset is the reliable
/// source of the user's current position.
@MainActor
final class LifecycleTableScrollPosition: ObservableObject {
    private weak var scrollView: NSScrollView?
    private var pendingOrigin: NSPoint?

    func resolve(in window: NSWindow?) {
        guard let contentView = window?.contentView,
              let tableView = contentView.lifecycleWasteBasketTableView()
        else {
            return
        }
        scrollView = tableView.enclosingScrollView
    }

    func captureBeforeSort() {
        pendingOrigin = scrollView?.contentView.bounds.origin
    }

    func restoreAfterSort() {
        guard let pendingOrigin else { return }
        self.pendingOrigin = nil

        // SwiftUI applies the new row order after the sort binding setter
        // returns. Restore on the following main-loop turn, when the native
        // table has its final document height.
        DispatchQueue.main.async { [weak self] in
            guard let self, let scrollView = self.scrollView else { return }
            let clipView = scrollView.contentView
            let documentHeight = scrollView.documentView?.bounds.height ?? 0
            let maximumY = max(0, documentHeight - clipView.bounds.height)
            let restoredOrigin = NSPoint(
                x: pendingOrigin.x,
                y: min(max(0, pendingOrigin.y), maximumY)
            )
            clipView.scroll(to: restoredOrigin)
            scrollView.reflectScrolledClipView(clipView)
        }
    }
}

/// Locates the AppKit table generated by SwiftUI and triggers restoration only
/// after a sort revision has caused the rows to be rebuilt.
struct LifecycleTableScrollProbe: NSViewRepresentable {
    let position: LifecycleTableScrollPosition
    let sortRevision: Int

    func makeNSView(context: Context) -> LifecycleTableScrollProbeView {
        let view = LifecycleTableScrollProbeView()
        view.position = position
        view.resolveTable()
        return view
    }

    func updateNSView(_ nsView: LifecycleTableScrollProbeView, context: Context) {
        nsView.position = position
        nsView.sortRevision = sortRevision
        nsView.resolveTable()
    }
}

final class LifecycleTableScrollProbeView: NSView {
    weak var position: LifecycleTableScrollPosition?
    var sortRevision = 0 {
        didSet {
            guard sortRevision != oldValue else { return }
            position?.restoreAfterSort()
        }
    }

    override func viewDidMoveToWindow() {
        super.viewDidMoveToWindow()
        resolveTable()
    }

    func resolveTable() {
        DispatchQueue.main.async { [weak self] in
            guard let self else { return }
            self.position?.resolve(in: self.window)
        }
    }
}

private extension NSView {
    func lifecycleWasteBasketTableView() -> NSTableView? {
        if let tableView = self as? NSTableView,
           tableView.tableColumns.contains(where: {
               $0.headerCell.stringValue == "Deleted"
           }) {
            return tableView
        }
        for subview in subviews {
            if let tableView = subview.lifecycleWasteBasketTableView() {
                return tableView
            }
        }
        return nil
    }
}
